In [1]:
import numpy as np # linear algebra


In [2]:
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)



In [3]:
from keras.preprocessing.text import Tokenizer


Using TensorFlow backend.


In [4]:
from keras.preprocessing.sequence import pad_sequences


In [5]:
from keras.models import Sequential


In [6]:
from keras.layers import Dense, Embedding, LSTM


In [7]:
from sklearn.model_selection import train_test_split


In [8]:
from keras.utils.np_utils import to_categorical


In [9]:
import re

In [10]:
#ML

In [32]:
data = pd.read_csv(r'Sentiment.csv')

# Keeping only the neccessary columns
data = data[['text','sentiment']]
print(len(data))

13871


In [33]:
data

text sentiment
0      RT @NancyLeeGrahn: How did everyone feel about...   Neutral
1      RT @ScottWalker: Didn't catch the full #GOPdeb...  Positive
2      RT @TJMShow: No mention of Tamir Rice and the ...   Neutral
3      RT @RobGeorge: That Carly Fiorina is trending ...  Positive
4      RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  Positive
5      RT @GregAbbott_TX: @TedCruz: "On my first day ...  Positive
6      RT @warriorwoman91: I liked her and was happy ...  Negative
7      Going on #MSNBC Live with @ThomasARoberts arou...   Neutral
8      Deer in the headlights RT @lizzwinstead: Ben C...  Negative
9      RT @NancyOsborne180: Last night's debate prove...  Negative
10     @JGreenDC @realDonaldTrump In all fairness #Bi...  Negative
11     RT @WayneDupreeShow: Just woke up to tweet thi...  Positive
12     Me reading my family's comments about how grea...  Negative
13     RT @ArcticFox2016: RT @AllenWestRepub "Dear @J...   Neutral
14     RT @pattonoswalt: I loved Scott Walker as Mark...  Positive
15     Hey @ChrisChristie exploiting the tragedy of 9...  Negative
16     RT @CarolCNN: #DonaldTrump under fire for comm...  Negative
17     RT @johncardillo: Guess who had most speaking ...  Negative
18     reason comment is funny 'in case you're ignora...  Negative
19     RT @PamelaGeller: Huckabee: Paying for transge...  Negative
20     RT @ChuckNellis: Cruz has class &amp; truth, t...  Positive
21     RT @mchamric: RT “@TeaTraitors: #GOPDebate was...  Negative
22     RT @erinmallorylong: No *I* hate Planned Paren...  Negative
23     RT @thekevinryder: #GOPDebate (Vine by @dabull...   Neutral
24     RT @MrPooni: Fox News trying to convince us yo...  Negative
25     #GOPDebate rankings: worst to be performance -...  Negative
26     RT @TheBaxterBean: Scott Walker's Abortion Ban...  Negative
27     RT @feministabulous: It's not a competition, b...  Negative
28     RT @mch7576: RT “@TeaTraitors: #GOPDebate was ...  Negative
29     RT @HillaryClinton: Watch the #GOPdebate? Bet ...  Negative
...                                                  ...       ...
13841  RT @EthanObama: Did Trump just admit he gives ...  Negative
13842  Trump and most of the World! Just look at the ...   Neutral
13843  @JessicaValenti they all need coif reform. #GO...  Negative
13844  Wow, Rubio's ear-to-head ratio is all messed u...  Negative
13845  RT @the818: Let's play "how fast can we distan...  Negative
13846  Me watching the GOP Debates. #gopdebates https...   Neutral
13847  RT @mjtbaum: GOD is making an appearance at th...  Positive
13848  RT @PuestoLoco: .@NewDay Cancel the primaries....  Negative
13849  RT @kaylasmith4791: Really enjoyed everything ...  Positive
13850  RT @RWSurferGirl: The candidates don't have to...  Negative
13851  #GOPDebate in a nutshell via Vote True Blue 20...  Negative
13852  RT @erinmallorylong: No *I* hate Planned Paren...  Negative
13853  RT @BrendanKKirby: If @JohnKasich hasn't wrapp...  Negative
13854  RT @monaeltahawy: I'll tell you the one good t...  Negative
13855  while pro-life nonsense @ the #GOPDebate was n...  Negative
13856  GOP respects life....just not black ones. #GOP...  Negative
13857  This is why I don't watch Fox News, they're al...  Negative
13858  @marcorubio came out of the gate like a true l...  Positive
13859  Best line of #GOPDebate was "Immigration witho...  Positive
13860  People who say they are #prolife are usually a...  Negative
13861  RT @RWSurferGirl: Why should @realDonaldTrump ...  Negative
13862  RT @RWSurferGirl: Trump has got it right, nobo...  Positive
13863  So trans soldiers can die for you Huckabee but...  Negative
13864  RT @RWSurferGirl: Is it just me or does anyone...  Negative
13865  RT @RWSurferGirl: Fox is cherry picking the ca...  Negative
13866  RT @cappy_yarbrough: Love to see men who will ...  Negative
13867  RT @georgehenryw: Who thought Huckabee exceede...  Positive
13868  RT @Lrihendry: #TedCruz As President, I will a...  Positive
13869  RT @JRehling: #GOPDebate 

In [34]:

data['text'] = data['text'].apply(lambda x: x.lower())
data['text'] = data['text'].apply((lambda x: re.sub('[^a-zA-z0-9\s]','',x)))

#print(data[ data['sentiment'] == 'Positive'].size)
#print(data[ data['sentiment'] == 'Negative'].size)

for idx,row in data.iterrows():
    row[0] = row[0].replace('rt',' ')
    
batch_size = 5000
tokenizer = Tokenizer(nb_words=batch_size, split=' ')

tokenizer.fit_on_texts(data['text'].values)
X = tokenizer.texts_to_sequences(data['text'].values)

maxx = 0
c=0
for ll in X:
    c=len(ll)
    if c>maxx:
        maxx=c
print('Max',maxx)
X = pad_sequences(X)
print(len(X[0]))

C:\Users\Bharathi\Anaconda3\lib\site-packages\keras_preprocessing\text.py:178: UserWarning: The `nb_words` argument in `Tokenizer` has been renamed `num_words`.
  warnings.warn('The `nb_words` argument in `Tokenizer` '


Max 29
29


In [35]:
data

text sentiment
0        nancyleegrahn how did everyone feel about th...   Neutral
1        scottwalker didnt catch the full gopdebate l...  Positive
2        tjmshow no mention of tamir rice and the gop...   Neutral
3        robgeorge that carly fiorina is trending  ho...  Positive
4        danscavino gopdebate w realdonaldtrump deliv...  Positive
5        gregabbott_tx tedcruz on my first day i will...  Positive
6        warriorwoman91 i liked her and was happy whe...  Negative
7      going on msnbc live with thomasarobe s around ...   Neutral
8      deer in the headlights   lizzwinstead ben cars...  Negative
9        nancyosborne180 last nights debate proved it...  Negative
10     jgreendc realdonaldtrump in all fairness billc...  Negative
11       waynedupreeshow just woke up to tweet this o...  Positive
12     me reading my familys comments about how great...  Negative
13       arcticfox2016   allenwestrepub dear jebbush ...   Neutral
14       pattonoswalt i loved scott walker as mark ha...  Positive
15     hey chrischristie exploiting the tragedy of 91...  Negative
16       carolcnn donaldtrump under fire for comments...  Negative
17       johncardillo guess who had most speaking tim...  Negative
18     reason comment is funny in case youre ignorant...  Negative
19       pamelageller huckabee paying for transgender...  Negative
20       chucknellis cruz has class amp truth that ge...  Positive
21       mchamric   teatraitors gopdebate was still c...  Negative
22       erinmallorylong no i hate planned parenthood...  Negative
23       thekevinryder gopdebate vine by dabulldawg88...   Neutral
24       mrpooni fox news trying to convince us young...  Negative
25     gopdebate rankings worst to be performance  ru...  Negative
26       thebaxterbean scott walkers abo ion ban allo...  Negative
27       feministabulous its not a competition but ho...  Negative
28       mch7576   teatraitors gopdebate was still cl...  Negative
29       hillaryclinton watch the gopdebate bet you f...  Negative
...                                                  ...       ...
13841    ethanobama did trump just admit he gives mon...  Negative
13842  trump and most of the world just look at the c...   Neutral
13843  jessicavalenti they all need coif reform gopde...  Negative
13844  wow rubios ea ohead ratio is all messed up but...  Negative
13845    the818 lets play how fast can we distance ou...  Negative
13846  me watching the gop debates gopdebates httpstc...   Neutral
13847    mjtbaum god is making an appearance at the g...  Positive
13848    puestoloco newday cancel the primaries fox p...  Negative
13849    kaylasmith4791 really enjoyed everything mar...  Positive
13850    rwsurfergirl the candidates dont have to att...  Negative
13851  gopdebate in a nutshell via vote true blue 201...  Negative
13852    erinmallorylong no i hate planned parenthood...  Negative
13853    brendankkirby if johnkasich hasnt wrapped up...  Negative
13854    monaeltahawy ill tell you the one good thing...  Negative
13855  while prolife nonsense  the gopdebate was not ...  Negative
13856    gop respects lifejust not black ones gopdebates  Negative
13857  this is why i dont watch fox news theyre all a...  Negative
13858  marcorubio came out of the gate like a true le...  Positive
13859  best line of gopdebate was immigration without...  Positive
13860  people who say they are prolife are usually an...  Negative
13861    rwsurfergirl why should realdonaldtrump pled...  Negative
13862    rwsurfergirl trump has got it right nobody w...  Positive
13863  so trans soldiers can die for you huckabee but...  Negative
13864    rwsurfergirl is it just me or does anyone el...  Negative
13865    rwsurfergirl fox is cherry picking the candi...  Negative
13866    cappy_yarbrough love to see men who will nev...  Negative
13867    georgehenryw who thought huckabee exceeded t...  Positive
13868    lrihendry tedcruz as president i will always...  Positive
13869    jrehling gopdebate dona

In [36]:
embed_dim = 128
lstm_out = 128
model = Sequential()
model.add(Embedding(batch_size, embed_dim,input_length = X.shape[1], dropout=0.2))
model.add(LSTM(lstm_out,return_sequences=True ,dropout_U=0.2, dropout_W=0.2))
model.add(LSTM(32,return_sequences=True))
model.add(LSTM(32))
model.add(Dense(3,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

C:\Users\Bharathi\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  after removing the cwd from sys.path.
C:\Users\Bharathi\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(128, return_sequences=True, dropout=0.2, recurrent_dropout=0.2)`
  """


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_12 (Embedding)     (None, 29, 128)           640000    
_________________________________________________________________
lstm_22 (LSTM)               (None, 29, 128)           131584    
_________________________________________________________________
lstm_23 (LSTM)               (None, 29, 32)            20608     
_________________________________________________________________
lstm_24 (LSTM)               (None, 32)                8320      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 99        
Total params: 800,611
Trainable params: 800,611
Non-trainable params: 0
_________________________________________________________________
None


In [37]:
print(data['sentiment'].values)
Y = pd.get_dummies(data['sentiment']).values
print(Y)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.33, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

['Neutral' 'Positive' 'Neutral' ... 'Positive' 'Negative' 'Positive']
[[0 1 0]
 [0 0 1]
 [0 1 0]
 ...
 [0 0 1]
 [1 0 0]
 [0 0 1]]
(9293, 29) (9293, 3)
(4578, 29) (4578, 3)


In [51]:
model.fit(X_train, Y_train, nb_epoch = 30, batch_size=32)

Epoch 1/30
  32/9293 [..............................] - ETA: 32s - loss: 0.7189 - acc: 0.6250

C:\Users\Bharathi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


9293/9293 [==============================] - 41s 4ms/step - loss: 0.5559 - acc: 0.7751
Epoch 2/30
9293/9293 [==============================] - 40s 4ms/step - loss: 0.4904 - acc: 0.8057
Epoch 3/30
9293/9293 [==============================] - 41s 4ms/step - loss: 0.4367 - acc: 0.8280
Epoch 4/30
9293/9293 [==============================] - 41s 4ms/step - loss: 0.3859 - acc: 0.8468
Epoch 5/30
9293/9293 [==============================] - 41s 4ms/step - loss: 0.3403 - acc: 0.8668
Epoch 6/30
9293/9293 [==============================] - 41s 4ms/step - loss: 0.3079 - acc: 0.8796
Epoch 7/30
9293/9293 [==============================] - 47843s 5s/step - loss: 0.2795 - acc: 0.8887
Epoch 8/30
9293/9293 [==============================] - 25s 3ms/step - loss: 0.2654 - acc: 0.8944
Epoch 9/30
9293/9293 [==============================] - 34s 4ms/step - loss: 0.2473 - acc: 0.8996
Epoch 10/30
9293/9293 [==============================] - 36s 4ms/step - loss: 0.2344 - acc: 0.9048
Epoch 11/30
9293/9293 [=====

In [52]:
z=np.array(X_test[9]).reshape(1,29)

In [53]:
z

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0, 3828,  518, 2438,    9,   69, 1070, 1303,   53,  194,
           2,  117,  465,   68,  569,    1,  822]])

In [54]:
model.predict(z)

array([[9.9996853e-01, 2.1743172e-05, 9.7217553e-06]], dtype=float32)

In [55]:
Y_test[9]

array([1, 0, 0], dtype=uint8)

In [56]:
s1 = "john is a nice guy you would love to work with him"
s2 = "that was a bummer and an epic fail movie just dont go to watch"
hh = tokenizer.texts_to_sequences([s1])


In [57]:
hh

[[417, 6, 7, 684, 393, 12, 68, 223, 4, 476, 42, 81]]

In [58]:
X_test[9].shape

(29,)

In [59]:
hh = pad_sequences(hh, maxlen=29)

In [60]:
hh=np.array(hh[0]).reshape(1,29)

In [61]:
model.predict(hh)

array([[0.8159997 , 0.00303723, 0.18096308]], dtype=float32)

In [62]:
model.save('sentiment.h5')

In [63]:
import pickle
pickle.dump(tokenizer,open('token.pickle','wb'))